#ifndef PROBLEM_h__
#define PROBLEM_h__
#include <random>
#include "../Objects/Node.hpp"

class RNG{
public:
    int64_t seed = 0;
    RNG();
};

class Problem{
public:
    //Variables pertaining to the problem, if any.
    Variable* variables = nullptr;
    //The problem generated by the program.
    Node* problem = nullptr;
    //The correct answer(s).
    Node* answer = nullptr;
    //The user's provided answer.
    Node* response = nullptr;
    
    //This generates a problem.
    virtual Node* generate() = 0;
    //Give the user a question relating to the problem.
    virtual void prompt() = 0;
    //Await the user's response and respond based on it.
    virtual void getResponse() = 0;
};
#endif